import json
from pathlib import Path
from typing import Any, Dict, Optional

from mcp.server.fastmcp import Context

from rhinoclaw.server import logger, mcp
from rhinoclaw.utils.errors import ErrorCode
from rhinoclaw.utils.responses import from_exception, ok

_CATALOG_PATH = Path(__file__).parent.parent / "static" / "gh_components.json"
_catalog_cache: Optional[Dict[str, Any]] = None


def _catalog() -> Dict[str, Any]:
    global _catalog_cache
    if _catalog_cache is None:
        with open(_CATALOG_PATH, encoding="utf-8") as f:
            _catalog_cache = json.load(f)
    return _catalog_cache


def _score(component: Dict[str, Any], query: str) -> int:
    """Rank: exact name > exact nick > name prefix > name/nick substring >
    description substring. 0 = no match."""
    name = (component.get("name") or "").lower()
    nick = (component.get("nick") or "").lower()
    desc = (component.get("desc") or "").lower()
    if name == query:
        return 100
    if nick == query:
        return 90
    if name.startswith(query):
        return 80
    if query in name:
        return 60
    if query in nick:
        return 50
    tokens = query.split()
    if len(tokens) > 1 and all(token in name for token in tokens):
        return 55  # all words appear in the name (any order)
    if any(token in name for token in tokens):
        return 40
    if all(token in desc for token in tokens):
        return 30
    return 0


@mcp.tool()
def find_gh_component(
    ctx: Context,
    query: str,
    category: Optional[str] = None,
    limit: int = 8,
    include_obsolete: bool = False,
) -> str:
    """Look up Grasshopper components — ground truth instead of guessing.

    Searches the introspected component catalog (every component installed
    in the connected Rhino, including plugins like VisualARQ/Kangaroo/
    Pufferfish) by name, nickname, or description. **Always look up GUIDs
    and port names here before authoring graphs** with
    `build_gh_definition` / wiring — hallucinated GUIDs and port names are
    the #1 authoring failure.

    Pure offline lookup over `static/gh_components.json` (no Rhino call).
    The catalog is generated by live introspection of
    `Grasshopper.Instances.ComponentServer`; regenerate after installing
    new GH plugins.

    Parameters:
    - query: Name, nickname, or description words
      (e.g. "Extrude", "Pt", "boolean difference solid").
    - category: Optional filter (e.g. "Surface", "Curve", "VisualARQ").
    - limit: Max results (default 8).
    - include_obsolete: Include components flagged obsolete by GH.

    Returns:
        {"success": true, "data": {"matches": [{
            "guid": "962034e9-cc27-4394-afc4-5c16e3447cf9",
            "name": "Extrude", "nick": "Extr",
            "cat": "Surface", "sub": "Freeform",
            "in":  [{"n": "Base", "nn": "B", "t": "Geometry"}, ...],
            "out": [{"n": "Extrusion", "nn": "E", "t": "Geometry"}],
            "desc": "..."}],
         "catalog": {"component_count": 2534, "rhino_version": "8.31...",
                     "generated": "2026-06-12"}}}
    """
    try:
        if not query or not query.strip():
            raise ValueError("query is required")
        q = query.strip().lower()
        cat_filter = category.strip().lower() if category else None
        limit = max(1, min(int(limit), 50))

        catalog = _catalog()
        scored = []
        for component in catalog["components"]:
            if not include_obsolete and component.get("obsolete"):
                continue
            if cat_filter and (component.get("cat") or "").lower() != cat_filter:
                continue
            score = _score(component, q)
            if score:
                name = component.get("name") or ""
                # tie-break: shorter name = more canonical/specific
                scored.append((score, len(name), name, component))
        scored.sort(key=lambda t: (-t[0], t[1], t[2]))
        matches = [c for _, _, _, c in scored[:limit]]

        meta = catalog.get("meta", {})
        if not matches:
            categories = sorted(
                {c.get("cat") or "" for c in catalog["components"]} - {""})
            return json.dumps(ok(
                message=f"No component matches '{query}'"
                        + (f" in category '{category}'" if category else ""),
                data={"matches": [], "hint": "try fewer/other words or no "
                      "category filter", "categories": categories,
                      "catalog": {"component_count": meta.get("component_count"),
                                  "generated": meta.get("generated")}},
            ))

        return json.dumps(ok(
            message=f"{len(matches)} match(es) for '{query}' — best: "
                    f"{matches[0]['name']} ({matches[0]['guid']})",
            data={"matches": matches,
                  "catalog": {"component_count": meta.get("component_count"),
                              "rhino_version": meta.get("rhino_version"),
                              "generated": meta.get("generated")}},
        ))
    except Exception as e:
        logger.error(f"Error searching GH components: {e}")
        return json.dumps(from_exception(e, code=ErrorCode.INVALID_PARAMS))
